#CONFIG GERAL -------------------------------------------------------------------------------------
microservice:
  log:
    config: https://raw.githubusercontent.com/FabioNazario/config-repo/main/logback.xml
  jwt:
    secret: "2dfb811abb93f5644eaad865c4e466020a787d17d74b4f3c6ad2a07f8a7c796a"

#MONSTRO CONFIG COM H2
  monstro:
    application:
      name: monstro
    datasource:
      url: jdbc:h2:mem:monstro
      driver-class-name: org.h2.Driver
      username: sa
      password: 
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

#MONSTRO CONFIG -----------------------------------------------------------------------------------
#  monstro:
#    application:
#      name: monstro
#    datasource:
#      url: jdbc:mysql://localhost:3306/monstro?createDatabaseIfNotExist=true
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#    jpa:
#      database-platform: org.hibernate.dialect.MySQL5Dialect
 
