microservice:
  example:
    greeting: "Estou sendo importado do git"
  jwt:
    secret: "123123sdasdgahksjgdg"
  datasource:
    user: "root"
    pass: "12345645"

monstro:
  application:
    name: testeTeste

syslog:
  config: https://raw.githubusercontent.com/FabioNazario/config-repo/main/logback.xml
